baseURL = "https://fedegarcia.com.ar/"
languageCode = "en-us"
title = "Federico García | Jr. Software Developer"
theme = "SimpleIntro"

[params]
    favicon = "/favicon.ico"
    mainbg = "/image/header.jpg"
    name = "Federico García"
    mainTitle = " "
    mainText = " "